name: Load version manifest
runs:
  using: composite
  steps:
    - shell: pwsh
      run: |
        $BRANCH="${env:GITHUB_REF}".Replace("refs/heads/", "")
        $REPO="${env:GITHUB_REPOSITORY}"
        Invoke-WebRequest -UseBasicParsing -Headers @{"Cache-Control"="no-cache"} "https://raw.githubusercontent.com/$REPO/$BRANCH/common.ps1" -OutFile "./common.ps1"
        if (-not (Test-Path -Path "./common.ps1")) { throw "Script common.ps1 not found." }
        ./common.ps1 $true
        $GITHUB_ENV_RAW=(Get-Content -Path "${Env:GITHUB_ENV}")
        $GITHUB_ENV=[Ordered]@{}
        ($GITHUB_ENV_RAW | %{ $tmp=$_.Split('=') ; $GITHUB_ENV[$tmp[0]]=$tmp[1] })
        Write-Output $GITHUB_ENV_RAW
        if (-not ($GITHUB_ENV.Contains("DOCFX"))) { throw "Failed to properly load version manifest." }
