param(
    [string] $port="8080",
    [Switch] $cleanMetadata=$false,
    [Switch] $cleanOnly=$false,
    [int] $strategyType=1
)

if(-not (($strategyType -ne 0) -band(($strategyType -band ($strategyType - 1)) -eq 0))) { throw "Strategy type argument must be a power of 2!" }

$global:ProgressPreference='SilentlyContinue'
Invoke-WebRequest -UseBasicParsing -Headers @{"Cache-Control"="no-cache"} "https://raw.githubusercontent.com/altmp/altv-docs/$(git rev-parse --abbrev-ref HEAD)/common.ps1" -OutFile "./common.ps1" 2>&1 >$null
$global:ProgressPreference='Continue'
if($err -ne $null -or -not (Test-Path "./common.ps1")) { throw "Script common.ps1 not found." }
. "./common.ps1" $true

$strategy=[StrategyType]$strategyType

try
{
    $cwd=(Get-Location).Path
    $tmpd="${env:TMP}/altv-docs"
    New-Item -ItemType "Directory" -Path "$tmpd" 2>&1 >$null

    if($cleanOnly) { exit }

    foreach($el in $requiredRepos.GetEnumerator()) {
        if (-not ($el.Value["strategy"].HasFlag($strategy))) {
            continue
        }
        Run-Task "Checkout $($el.Value["name"]) repository" {
            if(Test-Path $el.Key) {
                Set-Location -Path $el.Key
                git fetch --depth 1 "origin" $el.Value["ref"]
                if((git status -s -b) -like "*``[*behind *``]") {
                    git clean -d -x -f
                    git reset --hard "FETCH_HEAD"
                    Set-Location $cwd
                    Exit-Task (0x0)
                } else {
                    Set-Location $cwd
                    Exit-Task (-0x1)
                }
            }
            if (-not $el.Value["ref"]) {
                git clone $el.Value["repo"] --depth 1 --quiet
            } else {
                git clone $el.Value["repo"] --branch $el.Value["ref"] --depth 1 --quiet
            }
        }
    }

    foreach($el in $requiredPackages.GetEnumerator()) {
        if (-not ($el.Value["strategy"].HasFlag($strategy))) {
            continue
        }
        Run-Task "Downloading $($el.Value["name"]) package" {
            if(Test-Path $el.Value["predicate"]) { Exit-Task (-0x1) }
            FetchAndDownloadRelease $el.Value["repo"] "$tmpd/" $el.Value["archive_name"] $el.Value["version"]
        }
        Run-Task "Extracting $($el.Value["name"]) package" {
            if(Test-Path $el.Value["predicate"]) { Exit-Task (-0x1) }
            ExtractArchive "$tmpd/$($el.Value["archive_name"])" $el.Value["dest"]
        }
    }

    Run-Task "Tools version" {
        Set-Location $cwd
        $tools=[Ordered]@{
            "Node.js"=(node -v);
            "Yarn/npm"=GetNodePackageVersion;
            "Visual Studio"=GetVisualStudioVersion;
            "DocFx"=GetAssemblyVersion "./docfx/docfx.exe";
            "DocFx TypeScriptReference"=GetAssemblyVersion "./templates/docfx-plugins-typescriptreference/plugins/DocFx.*.dll";
            "DocFx AddImageModal"=GetAssemblyVersion "./templates/docfx-plugins-addimagemodal/plugins/DocFx.*.dll";
            "DocFx ExtractSearchIndex"=GetAssemblyVersion "./templates/docfx-plugins-extractsearchindex/plugins/DocFx.*.dll";
            "DocFx ExtractArticleAffix"=GetAssemblyVersion "./templates/docfx-plugins-extractarticleaffix/plugins/DocFx.*.dll";
            "TypeDoc"=GetNodePackageVersion "typedoc";
            "type2docfx"=GetNodePackageVersion "type2docfx";
        }
        Write-Information -Tags "Output" -MessageData ($tools | Format-Table | Out-String)
    }

    Run-Task "Generating JS project metadata" {
        Set-Location -Path "./altv-types/docs/"
        $pkgCmd=GetNodePackageManager
        if(-not $pkgCmd) { Exit-Task (0x1) }
        if(-not (Test-Path "../node_modules/")) { & $pkgCmd install }
        RunNodePackage "typedoc" --options "./typedoc.json"
        RunNodePackage "type2docfx" "./api/.manifest" "./api/" --basePath "." --sourceUrl "https://github.com/altmp/altv-types" --sourceBranch "master" --disableAlphabetOrder
        Set-Location $cwd
    } { ($requiredTasks["generate-js"]["strategy"]).HasFlag($strategy) }
    Run-Task "Generating C# project metadata" {
        if(IsVisualStudioInstalled) {
            ./docfx/docfx metadata "./coreclr-module/docs/docfx.json"
        } else {
            New-Item -Path "./coreclr-module/docs/api/toc.yml" -Value "# Autogenerated file to prevent missing file error`n[]`n" -Force
            Exit-Task (-0x1)
        }
    } { ($requiredTasks["generate-cs"]["strategy"]).HasFlag($strategy) }

    ./docfx/docfx build "docfx.json" --intermediateFolder "$tmpd/obj/" --serve -p $port
}
finally
{
    Set-Location $cwd
    PostCleanup
}
